site_name: X2WOTCCommunityHighlander
site_description: Online documentation for the X2WOTCCommunityHighlander
repo_url: https://github.com/X2CommunityCore/X2WOTCCommunityHighlander
edit_uri: ""
theme:
  name: readthedocs
  highlightjs: true
  hljs_languages:
    - ini
    - unrealscript
# FIXME: https://github.com/mkdocs/mkdocs/issues/2028
extra_javascript:
  - js/extra.js